<a href="https://colab.research.google.com/github/Adryn27/Data-Analytics/blob/main/BAKERY_SALES_TRANSACTION_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BAKERY SALES TRANSACTION PREDICTION

Dataset berasal dari Kaggle: https://www.kaggle.com/datasets/mittalvasu95/the-bread-basket

Melakukan install mlxtend terlebih dahulu sebelum mengimport algoritma dan melakukan pemodelan

In [ ]:
pip install mlxtend==0.23.1

In [ ]:
#import library
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
#Membaca data
data = pd.read_csv('bread basket.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20507 entries, 0 to 20506
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction      20507 non-null  int64
 1   Item             20507 non-null  object
 2   date_time        20507 non-null  object
 3   period_day       20507 non-null  object
 4   weekday_weekend  20507 non-null  object
dtypes: int64(1), object(4)
memory usage: 801.2+ KB

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Mengecek nilai kosong
print(data.isnull().sum())

Transaction        0
Item               0
date_time          0
period_day         0
weekday_weekend    0
dtype: int64

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Setelah dilakukan pengecekan, dataset tidak memiliki data yang bernilai null disetiap kolomnya, sehingga dataset aman digunakan walaupun tanpa pembersihan data terlebih dahulu

In [ ]:
#Menampilkan data
data

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

       Transaction           Item         date_time period_day weekday_weekend
0                1          Bread  30-10-2016 09:58    morning         weekend
1                2   Scandinavian  30-10-2016 10:05    morning         weekend
2                2   Scandinavian  30-10-2016 10:05    morning         weekend
3                3  Hot chocolate  30-10-2016 10:07    morning         weekend
4                3            Jam  30-10-2016 10:07    morning         weekend
...            ...            ...               ...        ...             ...
20502         9682         Coffee  09-04-2017 14:32  afternoon         weekend
20503         9682            Tea  09-04-2017 14:32  afternoon         weekend
20504         9683         Coffee  09-04-2017 14:57  afternoon         weekend
20505         9683         Pastry  09-04-2017 14:57  afternoon         weekend
20506         9684      Smoothies  09-04-2017 15:04  afternoon         weekend

[20507 rows x 5 columns]

In [ ]:
#Melihat duplikasi data
data.nunique()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Transaction        9465
Item                 94
date_time          9182
period_day            4
weekday_weekend       2
dtype: int64

Setelah melihat duplikasi data pada masing-masing kolom, terlihat bahwa kolom weekday_weekend hanya memiliki 2 data saja. Sehingga, dilakukan grouping data pada masing-masing nilai yakni weekday dan weekend untuk tujuan pencarian pola-pola pembelian berdasarkan waktu tersebut untuk membentuk penataan produk dan kombinasi paket yang cocok di kedua waktu tersebut.

In [ ]:
#Grouping Weekday
group_weekday=(data[data['weekday_weekend']=='weekday']
       .groupby(['Transaction','Item'])['Item']
       .count().unstack().reset_index().fillna(0)
       .set_index('Transaction'))
group_weekday.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Item,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Baguette,Bakewell,Bare Popcorn,Bowl Nic Pitt,Bread,...,Tea,The BART,The Nomad,Tiffin,Toast,Truffles,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
Transaction,,,,,,,,,,,,,,,,,,,,,
81,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Grouping Weekend
group_weekend=(data[data['weekday_weekend']=='weekend']
       .groupby(['Transaction','Item'])['Item']
       .count().unstack().reset_index().fillna(0)
       .set_index('Transaction'))
group_weekend.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Item,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Basket,Bowl Nic Pitt,Bread,...,Tea,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
Transaction,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Sebelum ke tahap pemodelan, dilakukan encoding data guna untuk menunjukkan bahwa jika kuantitas nya kurang dari 0 maka tetap ditulis dengan 0, jika kuantitas nya lebih dari 1 maka tetap akan ditulis 1. Ini dilakukan karena pada association rule yang dihitung adalah kehadiran dari item tersebut, bukan dari kuantitas.

In [ ]:
#Encoding data
def encode_qty(x):
  if x <= 0:
    return 0
  if x >= 1:
    return 1

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Encoding data grup weekday
encode_group_weekday=group_weekday.applymap(encode_qty)
encode_group_weekday.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<ipython-input-10-ab681facb27a>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  encode_group_weekday=group_weekday.applymap(encode_qty)

Item,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Baguette,Bakewell,Bare Popcorn,Bowl Nic Pitt,Bread,...,Tea,The BART,The Nomad,Tiffin,Toast,Truffles,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
Transaction,,,,,,,,,,,,,,,,,,,,,
81,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
83,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
84,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
85,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#Encoding data grup weekend
encode_group_weekend=group_weekend.applymap(encode_qty)
encode_group_weekend.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<ipython-input-11-0b64e6e0d1c3>:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  encode_group_weekend=group_weekend.applymap(encode_qty)

Item,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Basket,Bowl Nic Pitt,Bread,...,Tea,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
Transaction,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

Untuk mempersempit ruang lingkup dan melihat pola pembelian pelanggan yakni berupa apa saja item atau produk yang sering dibeli baik pada waktu weekday dan weekend dengan menetapkan minimal support 4% atau item yang sering muncul dari 4% atau lebih jumlah transaksi pada dataset.

In [ ]:
#Mengelompokkan item/produk yang sering dibeli pada weekday
frequent_itemsets_day=apriori(encode_group_weekday, min_support=0.04, use_colnames=True)
frequent_itemsets_day.sort_values('support', ascending=False)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support          itemsets
2   0.485598          (Coffee)
0   0.317819           (Bread)
9   0.149390             (Tea)
1   0.095850            (Cake)
6   0.087551          (Pastry)
10  0.084459   (Coffee, Bread)
7   0.075346        (Sandwich)
3   0.062002         (Cookies)
5   0.052726       (Medialuna)
11  0.052238    (Coffee, Cake)
4   0.051424   (Hot chocolate)
12  0.049634  (Coffee, Pastry)
13  0.048332     (Coffee, Tea)
8   0.041660            (Soup)

Dari hasil penjabaran pola-pola diatas, ditemukan bahwa.
1. Coffee menjadi item yang paling sering muncul atau dibeli sekitar 48,5% dari total transaksi.
2. Bread menjadi item yang paling sering muncul atau dibeli kedua sekitar 31,7% dari total transaksi.
3. Tea menempati posisi ketiga menjadi item yang sering muncul atau dibeli sekitar 14,9% dari total transaksi.
4. Cake menjadi item yang sering muncul atau dibeli sekitar 9,5% dari total transaksi.
5. Pastry menjadi item yang sering muncul atau dibeli sekitar 8,7% dari total transaksi.
6. Coffee dan Bread menjadi kelompok item yang sering muncul atau dibeli sekitar 8,4% dari total transaksi.
7. Sandwich menjadi item yang sering muncul atau dibeli sekitar 7,5% dari total transaksi.
8. Cookies menjadi item yang sering muncul atau dibeli sekitar 6,2% dari total transaksi.
9. Medialuna menjadi item yang sering muncul atau dibeli sekitar 5,2% dari total transaksi.
10. Coffee dan Cake menjadi kelompok item yang sering muncul atau dibeli sekitar 5,2% dari total transaksi.
11. Hot Chocolate menjadi item yang sering muncul atau dibeli sekitar 5,1% dari total transaksi.
12. Coffee dan Pastry menjadi kelompok item yang sering muncul atau dibeli sekitar 4,9% dari total transaksi.
13. Coffee dan tea menjadi kelompok item yang sering muncul atau dibeli sekitar 4,8% dari total transaksi.
14. Soup menjadi item yang sering muncul atau dibeli sekitar 4,1% dari total transaksi.

In [ ]:
#Mengelompokkan item/produk yang sering dibeli pada weekend
frequent_itemsets_end=apriori(encode_group_weekend, min_support=0.04, use_colnames=True)
frequent_itemsets_end.sort_values('support', ascending=False)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/mlxtend/frequent_patterns/fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support             itemsets
3   0.465060             (Coffee)
0   0.344578              (Bread)
13  0.130120                (Tea)
2   0.118675               (Cake)
14  0.100301      (Coffee, Bread)
9   0.083434             (Pastry)
7   0.078614          (Medialuna)
5   0.071084      (Hot chocolate)
10  0.065361           (Sandwich)
12  0.061145              (Scone)
15  0.059337       (Coffee, Cake)
18  0.052711        (Coffee, Tea)
1   0.051807            (Brownie)
16  0.047289  (Coffee, Medialuna)
8   0.045482             (Muffin)
17  0.043675     (Coffee, Pastry)
11  0.043072       (Scandinavian)
6   0.041566              (Juice)
4   0.040361            (Cookies)

Dari hasil penjabaran pola-pola diatas untuk kasus weekend, ditemukan bahwa.
1. Coffee menjadi item yang paling sering muncul atau dibeli sekitar 46,5% dari total transaksi.
2. Bread menjadi item yang paling sering muncul atau dibeli kedua sekitar 34,4% dari total transaksi.
3. Tea menempati posisi ketiga menjadi item yang sering muncul atau dibeli sekitar 13% dari total transaksi.
4. Cake menjadi item yang sering muncul atau dibeli sekitar 11,8% dari total transaksi.
5. Coffee dan Bread menjadi kelompok item yang sering muncul atau dibeli sekitar 10% dari total transaksi.
6. Pastry menjadi item yang sering muncul atau dibeli sekitar 8,3% dari total transaksi.
7. Medialuna menjadi item yang sering muncul atau dibeli sekitar 7,8% dari total transaksi.
8. Hot Chocolate menjadi item yang sering muncul atau dibeli sekitar 7,1% dari total transaksi.
9. Sanwich menjadi item yang sering muncul atau dibeli sekitar 6,5% dari total transaksi.
10. Scone menjadi item yang sering muncul atau dibeli sekitar 6,1% dari total transaksi.
11. Coffee dan Cake menjadi kelompok item yang sering muncul atau dibeli sekitar 5,9% dari total transaksi.
12. Coffee dan Tea menjadi kelompok item yang sering muncul atau dibeli sekitar 5,2% dari total transaksi.
13. Brownie menjadi item yang sering muncul atau dibeli sekitar 5,1% dari total transaksi.
14. Coffee dan Medialuna menjadi kelompok item yang sering muncul atau dibeli sekitar 4,7% dari total transaksi.
15. Muffin menjadi item yang sering muncul atau dibeli sekitar 4,5% dari total transaksi.
16. Coffee dan Pastry menjadi kelompok item yang sering muncul atau dibeli sekitar 4,3% dari total transaksi.
17. Scandinavian menjadi item yang sering muncul atau dibeli sekitar 4,3% dari total transaksi.
18. Juice menjadi item yang sering muncul atau dibeli sekitar 4,1% dari total transaksi.
19. Cookies menjadi item yang sering muncul atau dibeli sekitar 4% dari total transaksi.

In [ ]:
#Pembuatan Model Weekday
rules=association_rules(frequent_itemsets_day, metric='lift', min_threshold=1)
rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Coffee),(Cake),0.485598,0.095850,0.052238,0.107574,1.122310,0.005693,1.013137,0.211859
1,(Cake),(Coffee),0.095850,0.485598,0.052238,0.544992,1.122310,0.005693,1.130533,0.120534
2,(Coffee),(Pastry),0.485598,0.087551,0.049634,0.102212,1.167456,0.007119,1.016330,0.278842
3,(Pastry),(Coffee),0.087551,0.485598,0.049634,0.566914,1.167456,0.007119,1.187761,0.157200

Dari hasil model diatas ditemukan bahwa.
1. Aturan pertama (coffee – cake) memiliki aturan asosiasi yang positif tetapi lemah. Walaupun memiliki hubungan yang positif yang menunjukkan memiliki potensi untuk dibuat paket/combo, namun potensi yang didapat tidak signifikan. Hal ini dapat dilihat bahwa aturan ini jarang dibeli oleh pelanggan dan hanya 10,75% kemungkinan pelanggan membeli cake jika ia membeli coffee, serta rasio lift yang rendah hanya 1,12. Sehingga aturan ini tidak cocok dan tidak tepat untuk dibuat paket/combo dalam meningkatkan pembelian.
2. Aturan kedua (cake – coffee) memiliki aturan asosiasi yang positif tetapi lemah. Tingkat confidence yang dimiliki cukup tinggi sebesar 54.49%, sehingga memiliki potensi yang positif untuk dibuat paket/combo produk. Namun, sama halnya dengan aturan pertama (coffee – cake) dengan tingkat lift rasio yang rendah sebesar 1,12 serta support yang rendah sebesar 5,22%, membuat aturan ini tidak cocok untuk dibuat paket/combo produk dalam meningkatkan pembelian.
3. Aturan ketiga (coffee – pastry) memiliki aturan asosiasi yang positif tetapi lemah. Walaupun memiliki hubungan yang positif hingga memiliki potensi untuk dibuat paket/combo produk. Akan tetapi, potensi yang didapat tidak signifikan. Sehingga jangan mengharapkan pada aturan ini, karena aturan ini tidak cocok dan tidak tepat untuk dibuat paket/combo dalam meningkatkan pembelian dengan tingkat support dan confidence yang rendah, serta lift ratio yang rendah.
4. Aturan keempat (pastry - coffee) memiliki hubungan positif yang lemah. Walaupun tingkat confidence yang dimiliki cukup tinggi sebesar 56,67%. Akan tetapi aturan ini tidak cocok dibuat untuk paket/combo produk dalam meningkatkan pembelian. Hal ini dikarenakan hasil yang didapat tidak signifikan dengan tingkat support dan lift ratio yang rendah.

In [ ]:
#Pembuatan Model Weekend
rules=association_rules(frequent_itemsets_end, metric='lift', min_threshold=1)
rules

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Coffee),(Cake),0.465060,0.118675,0.059337,0.127591,1.075130,0.004146,1.010220,0.130631
1,(Cake),(Coffee),0.118675,0.465060,0.059337,0.500000,1.075130,0.004146,1.069880,0.079289
2,(Coffee),(Medialuna),0.465060,0.078614,0.047289,0.101684,1.293451,0.010729,1.025681,0.424112
3,(Medialuna),(Coffee),0.078614,0.465060,0.047289,0.601533,1.293451,0.010729,1.342493,0.246232
4,(Coffee),(Pastry),0.465060,0.083434,0.043675,0.093912,1.125587,0.004873,1.011564,0.208574
5,(Pastry),(Coffee),0.083434,0.465060,0.043675,0.523466,1.125587,0.004873,1.122563,0.121731

Dari hasil pemodelan diatas, ditemukan bahwa.
1. Aturan pertama (coffee – cake) memiliki hubungan positif yang lemah. Potensi atau hasil yang didapat tidak akan signifikan. Hal ini dapat dilihat pada tingkat support yang rendah hanya sebesar 5,93%, tingkat confidence yang hanya sebesar 12,75%, dan lift ratio hanya 1,07. Sehingga, aturan ini tidak cocok untuk dibuat paket/combo dalam meningkatkan pembelian.
2. Aturan kedua yakni (cake – coffee) memiliki hubungan positif yang lemah. Ini dibuktikan dengan lift ratio yang rendah sebesar 1,07 dan support sebesar 5,93%. Akan tetapi tingkat confidence sebesar 50%. Walau terlihat memiliki potensi berdasarkan tingkat confidence tersebut, namun hasil yang diperoleh tidak akan signifikan. Sehingga aturan ini tidak cocok untuk dibuat paket/combo produk dalam meningkatkan pembelian.
3. Aturan ketiga yakni (coffee – medialuna) memiliki hubungan positif yang lemah. Setelah melihat performa model yang ada, hasil yang diperoleh cukup rendah. Mulai dari support yang hanya 4,72%, confidence sebesar 10,16%, hingga lift ratio sebesar 1,29. Sehingga jika dibuat paket/combo produk pada aturan ini hasil yang diperoleh tidak akan signifikan. Jadi, penulis menyimpulkan bahwa aturan ini tidak tepat dibuat paket/combo produk dalam meningkatkan pembelian.
4. aturan keempat yakni (medialuna-coffee) memiliki hubungan positif yang lemah. Dengan tingkat confidence yang cukup tinggi yakni 60,15% yang membuat aturan ini dapat dibuat paket/combo produk. Akan tetapi perlu dilihat faktor lainnya yang cukup rendah, dengan tingkat support 4,72% dan lift ratio sebesar 1,29 yang membuat hasil didapat tidak signifikan, karena sebagian besar pelanggan membeli produk secara terpisah. Sehingga aturan ini tidak tepat dibuat paket/combo produk dalam meningkatkan pembelian.
5. aturan kelima yakni (coffee – pastry) memiliki hubungan positif yang lemah. Ini ditunjukkan dengan lift ratio sebesar 1,011 yakni lebih dari 1 namun masih mendekati 1 yang membuat lemah. Selain itu faktor lainnya dapat dilihat pada support dan confidence yang rendah. Sehingga aturan ini tidak tepat untuk dibuat paket/combo dalam meningkatkan pembelian dikarenakan hasil yang diperoleh tidak signifikan.
6. aturan keenam yakni (pastry – coffee) memiliki hubungan positif yang lemah. Walaupun tingkat confidence yang dimiliki cukup tinggi sebesar 52,34%. Namun lift ratio dan tingkat support cukup rendah. Sehingga aturan ini tidak tepat dibuat untuk paket/combo produk dalam meningkatkan pembelian.

Dari hasil analisis diatas dengan menggunakan algoritma apriori, dapat disimpulkan bahwa.
1. Pada weekday, bakery dapat melakukan penataan barang berupa bread, cake, pastry, sandwich, cookies, dan medialuna, serta menyediakan coffee, tea, hot chocolate, dan soup dengan tingkat support 4% dari transaksi. Sedangkan pada weekend, bakery dapat melakukan penataan barang berupa bread, cake, pastry, medialuna, sandwich, scone, brownie, muffin, scandinavian dan cookies, serta menyediakan coffee, tea, hot chocolate, dan juice dengan tingkat support 4% dari transaksi.
2. Pada weekday, coffee, bread, dan tea menjadi produk yang paling sering dibeli dengan tingkat support diatas 10% dari transaksi. Sedangkan pada weekend, coffee, bread, tea, dan cake menjadi produk yang paling sering dibeli dengan tingkat support diatas 10% dari transaksi. Sehingga, penulis merekomendasikan untuk memastikan stok produk tersebut tersedia untuk menghindari kehilangan peluang penjualan. Untuk tingkat support dibawah 10%, penulis dapat menyarankan untuk mempertimbangkan untuk mengurangi atau mengganti produk tersebut yang jarang dibeli.
3. Setelah dilakukan evaluasi performa model, sayangnya baik weekday maupun weekend tidak mencapai tujuan yang diharapkan yakni menetapkan paket/combo produk dalam meningkatkan pembelian.
4. Pada weekday, ditemukan kombinasi produk {cake,coffee} dan {pastry,coffee) dengan tingkat confidence yang cukup tinggi yang berarti pelanggan yang membeli cake maupun pastry ada kemungkinan ia juga membeli coffee. Ini berarti adanya hubungan positif dari kombinasi tersebut. Namun, dilihat dari performa model yang lain terutama support dan lift rasio yang rendah, ini membuktikan bahwa hasil yang diperoleh tidak akan signifikan untuk mendorong peningkatan pembelian. Hal ini dikarenakan mungkin saja pelanggan lebih memilih membeli produk secara terpisah, sehingga paket/combo produk tidak memberikan nilai tambah.
5. Pada weekend, ditemukan hal yang sama dengan waktu weekday dimana kombinasi produk {cake,coffee}, {medialuna,coffee}, dan {pastry,coffee} memiliki tingkat confidence yang cukup tinggi yang berarti pelanggan yang membeli cake atau medialuna atau pastry ada
kemungkinan ia juga membeli coffee. Akan tetapi performa model yang lain cukup rendah sehingga tidak memungkinkan dibuat paket/combo produk dalam meningkatkan pembelian.